-- H2 2.1.214;
;             
CREATE USER IF NOT EXISTS "GK" SALT 'a8ca7925da9f41bd' HASH '462c4f0dcf3fcc6e79fcb4aa1ed2bb8edbf0f4fd5075c0026b0aad88144cf616' ADMIN;         
CREATE MEMORY TABLE "PUBLIC"."TB_COMPLAINT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "DATE" DATE,
    "STATUS" INTEGER,
    "TEXT" CHARACTER VARYING,
    "TIME" CHARACTER VARYING(255),
    "USER_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."TB_COMPLAINT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID"); 
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.TB_COMPLAINT;           
INSERT INTO "PUBLIC"."TB_COMPLAINT" VALUES
(1, DATE '2022-07-25', 1, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '12:23', 8),
(2, DATE '2022-06-05', 2, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '17:15', 9),
(3, DATE '2022-05-21', 0, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '18:30', 10),
(4, DATE '2022-04-12', 1, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '09:40', 11),
(5, DATE '2022-03-20', 0, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias.', '15:48', 12),
(6, DATE '2022-02-12', 0, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga.', '20:23', 13),
(7, DATE '2022-01-30', 1, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit.', '22:10', 14),
(8, DATE '2021-12-02', 2, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '03:18', 15),
(9, DATE '2021-11-18', 1, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '05:38', 16),
(10, DATE '2021-10-08', 2, 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nobis cupiditate inventore, illum reiciendis molestias fuga voluptas commodi ipsam non aliquam deleniti magnam vel esse eos? Nulla dignissimos cum ab adipisci.', '08:40', 17);         
CREATE MEMORY TABLE "PUBLIC"."TB_DELIVERY"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 11) NOT NULL,
    "DATE" DATE,
    "DESCRIPTION" CHARACTER VARYING,
    "IMG_URL" CHARACTER VARYING(255),
    "STATUS" INTEGER,
    "TIME" CHARACTER VARYING(255),
    "TO_USER" BIGINT
);     
ALTER TABLE "PUBLIC"."TB_DELIVERY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");  
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.TB_DELIVERY;            
INSERT INTO "PUBLIC"."TB_DELIVERY" VALUES
(1, DATE '2022-07-25', U&'Livro cole\00e7\00e3o Senhor dos An\00e9is', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/1-big.jpg', 1, '15:20', 8),
(2, DATE '2022-07-29', 'Smart Tv', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/2-big.jpg', 1, '21:10', 9),
(3, DATE '2022-08-02', 'NoteBook Top', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/3-big.jpg', 1, '22:45', 10),
(4, DATE '2022-08-12', U&'Desktop gamer pr\00f3 ultra.', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/4-big.jpg', 2, '07:12', 11),
(5, DATE '2022-09-25', 'Livro Rail for Dummies', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/5-big.jpg', 2, '12:15', 12),
(6, DATE '2023-01-05', 'Notebook meia boca', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/6-big.jpg', 3, '17:28', 13),
(7, DATE '2023-01-30', 'Notebook de novo', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/7-big.jpg', 1, '15:32', 14),
(8, DATE '2024-02-15', U&'Notebook pregui\00e7a', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/8-big.jpg', 0, '15:48', 8),
(9, DATE '2024-03-21', 'Notebook Notebook Notebook', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/9-big.jpg', 0, '14:18', 10),
(10, DATE '2024-04-02', U&'\00daltimo Notebook', 'https://raw.githubusercontent.com/devsuperior/dscatalog-resources/master/backend/img/10-big.jpg', 0, '19:10', 13);    
CREATE MEMORY TABLE "PUBLIC"."TB_REPORT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 13) NOT NULL,
    "DATE" DATE,
    "TEXT" CHARACTER VARYING,
    "TIME" CHARACTER VARYING(255),
    "USER_ID" BIGINT
);            
ALTER TABLE "PUBLIC"."TB_REPORT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");    
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.TB_REPORT;              
INSERT INTO "PUBLIC"."TB_REPORT" VALUES
(1, DATE '2022-07-25', 'Queda de energia das 05:00 as 06:22', '05:00', 1),
(2, DATE '2022-07-29', 'Morador 1818 retirou sua encomenda', '15:15', 2),
(3, DATE '2022-08-03', U&'Briga de casal e Pol\00edcia acionado. Sindicos cientes.', '18:22', 3),
(4, DATE '2022-08-03', 'Elevador parado. BTA acionado e aguardando retorno.', '21:22', 4),
(5, DATE '2022-08-04', U&'Morador X reportou vazamento de \00e1gua', '07:00', 1),
(6, DATE '2022-08-04', 'Morador reclamou das esteiras da academia quebrada', '15:15', 1),
(7, DATE '2022-08-04', U&'Lampadas queimadas aqui e acol\00e1', '19:22', 2),
(8, DATE '2022-08-04', U&'Novo h\00f3spede para o 403', '21:22', 2),
(9, DATE '2022-08-05', U&'Piscineiro interditou a piscina at\00e1 amanh\00e3', '08:00', 3),
(10, DATE '2022-08-05', 'Cistena e gerador verificados e tudo ok.', '16:25', 3),
(11, DATE '2022-08-05', 'Moradores informaram a troca de carro para HB20 Prata', '20:42', 4),
(12, DATE '2022-08-05', U&'Moradores utilizaram da churrasqueira e n\00e3o limparam', '23:22', 4);             
CREATE MEMORY TABLE "PUBLIC"."TB_ROLE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "AUTHORITY" CHARACTER VARYING(255)
);  
ALTER TABLE "PUBLIC"."TB_ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");      
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.TB_ROLE; 
INSERT INTO "PUBLIC"."TB_ROLE" VALUES
(1, 'ROLE_ADMIN'),
(2, 'ROLE_USER'),
(3, 'ROLE_VISITOR');            
CREATE MEMORY TABLE "PUBLIC"."TB_USER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 18) NOT NULL,
    "BIRTH_DATE" DATE,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "PHONE" CHARACTER VARYING(255),
    "UNIT" INTEGER
);       
ALTER TABLE "PUBLIC"."TB_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D1" PRIMARY KEY("ID");     
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.TB_USER;
INSERT INTO "PUBLIC"."TB_USER" VALUES
(1, DATE '1995-07-25', 'portaria1@gmail.com', 'Portaria1', '$2a$10$5c5V4aBMxGArBzcjVndpMOIPe.2458hQ186I0Q5.VcL5Zoc8l4466', '988888888', NULL),
(2, DATE '1996-08-26', 'portaria2@gmail.com', 'Portaria2', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '977777777', NULL),
(3, DATE '1997-09-27', 'portaria3@gmail.com', 'Portaria3', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '966666666', NULL),
(4, DATE '1998-10-28', 'portaria4@gmail.com', 'Portaria4', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '955555555', NULL),
(5, DATE '1987-11-13', 'sindico@gmail.com', 'Sindico', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '977777777', NULL),
(6, DATE '1988-12-18', 'subsindico1@gmail.com', 'SubSindico', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '977777777', NULL),
(7, DATE '1960-06-16', 'administradora@gmail.com', 'Administradora', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '977777777', NULL),
(8, DATE '1982-01-13', 'biuno@gmail.com', 'Biuno', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '996578965', 101),
(9, DATE '1979-05-23', 'bubu@gmail.com', 'Bubu', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '89654124', 202),
(10, DATE '1992-02-19', 'joselito@gmail.com', 'Joselito', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '89654124', 303),
(11, DATE '2012-10-31', 'zelele@gmail.com', U&'Z\00e9 Lel\00e9', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '912354678', 404),
(12, DATE '2001-01-16', 'tchongo@gmail.com', 'Tchongo', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '998435716', 505),
(13, DATE '1980-01-30', 'jedai@gmail.com', 'Jedai', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '9999657482', 606),
(14, DATE '1990-12-26', 'ninja@gmail.com', 'Ninja', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '9886574256', 707),
(15, DATE '1988-09-19', 'tio@gmail.com', 'tio', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '9987453214', 808),
(16, DATE '1981-04-22', 'topper@gmail.com', 'topper', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '9654784211', 909),
(17, DATE '1987-07-20', 'pombolezo@gmail.com', 'Pombo Lezo', '$2a$10$JNZAL0iBKhBZ4qNKnmv62etMP6COUduvV5kREkpciwhtko68hUWLu', '988765142', 1010);   
CREATE MEMORY TABLE "PUBLIC"."TB_USER_ROLE"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);               
ALTER TABLE "PUBLIC"."TB_USER_ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("USER_ID", "ROLE_ID"); 
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.TB_USER_ROLE;           
INSERT INTO "PUBLIC"."TB_USER_ROLE" VALUES
(1, 2),
(2, 2),
(3, 2),
(4, 2),
(5, 1),
(6, 1),
(7, 3),
(8, 3),
(9, 3),
(10, 3),
(11, 3),
(12, 3),
(13, 3),
(14, 3),
(15, 3),
(16, 3),
(17, 3);   
ALTER TABLE "PUBLIC"."TB_USER_ROLE" ADD CONSTRAINT "PUBLIC"."FK7VN3H53D0TQDIMM8CP45GC0KL" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."TB_USER"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."TB_USER_ROLE" ADD CONSTRAINT "PUBLIC"."FKEA2OOTW6B6BB0XT3PTL28BYMV" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."TB_ROLE"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."TB_DELIVERY" ADD CONSTRAINT "PUBLIC"."FK425HC2MU8KX7R0ENEGLMV1RY6" FOREIGN KEY("TO_USER") REFERENCES "PUBLIC"."TB_USER"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."TB_REPORT" ADD CONSTRAINT "PUBLIC"."FK92G5VKSC5OOL0FSCR54X9PSTT" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."TB_USER"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."TB_COMPLAINT" ADD CONSTRAINT "PUBLIC"."FKTIIH14R4WGATRV5D2C9DGSAJ3" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."TB_USER"("ID") NOCHECK; 
